### ISSUE TITLE
Port 3000 clashes with the port used by cold_start

### ISSUE THREAD

**Issue by libbymiller** [radiodan-archive/radiodan-example#1]
/var/lib/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)

-> we just need to change the line in ./bin/start:

builder.use      :web_server, WebApp, :port => 3000

to a different port - but we need to watch out for the effects on vagrant, which makes 3000 accessible outside the VM

**Comment by andrewn** [comment]
This should be fixed in radiodan/cold_start@2b6cdb2
